version: '3.8'
services:
  php: 
    build: './docker/php'
    user: ${UID:-1000}:${GID:-1000}
    ports:
      - ${PHP_PORT:-8080}:80
    volumes:
      - ./:/var/www/html
    environment:
      - DB_HOST=db
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
    depends_on:
      - db
    command: php -S 0.0.0.0:80 -t .

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  db_data: